In [ ]:
# dot product of two vectors
import numpy as np
a=[1,2,3]
b=[4,5,6]

dot_manual=0
for i in range(len(a)):
    dot_manual+=a[i]*b[i]
print("Dot product (manual):", dot_manual)

dot_numpy=np.dot(a,b)
print("Dot product (NumPy):", dot_numpy)
    



Dot product (manual): 32
Dot product (NumPy): 32


In [9]:
#matrix multiplication
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

result_manual=np.zeros((2,2))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            result_manual[i,j]+=A[i,k]*B[k,j]
print("Matrix multiplication (manual):\n", result_manual)

result_numpy=np.matmul(A,B)
print("Matrix multiplication (NumPy):\n", result_numpy)

Matrix multiplication (manual):
 [[ 58.  64.]
 [139. 154.]]
Matrix multiplication (NumPy):
 [[ 58  64]
 [139 154]]


In [10]:
M=np.array([[10,20,30],
            [40,50,60]])

V=np.array([1,2,3])

result=M+V

print("Original Matrix:\n", M)
print("Vector:\n", V)
print("Matrix and vector addition (broadcasting):\n", result)

Original Matrix:
 [[10 20 30]
 [40 50 60]]
Vector:
 [1 2 3]
Matrix and vector addition (broadcasting):
 [[11 22 33]
 [41 52 63]]
